# Generated by Django 4.2.5 on 2023-10-05 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_tiposexames_tiposexame_solicitacaoexame_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacaoexame',
            name='exame',
        ),
        migrations.RemoveField(
            model_name='solicitacaoexame',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='PedidosExame',
        ),
        migrations.DeleteModel(
            name='SolicitacaoExame',
        ),
        migrations.DeleteModel(
            name='TiposExame',
        ),
    ]
